import { Router } from "express";

import { getUserSummary } from "../controller/user.controller";
import { verifyToken } from "../middlewares/verifyToken";

const router = Router();

/**
 * @openapi
 * /llm/api/v1/user/generate-summary:
 *   post:
 *     summary: Generate a user summary
 *     description: Accepts academic and personal data to generate an AI-driven user context/summary.
 *     security:
 *       - BearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/UserSummaryData'
 *     responses:
 *       200:
 *         description: User summary generated successfully
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/ApiResponse'
 *                 - type: object
 *                   properties:
 *                     data:
 *                       type: string
 *                       example: "User summary generated by LLM..."
 */
router.route("/generate-summary").post(verifyToken, getUserSummary);

export default router;
