export const domain = {
  WEB_DEVELOPMENT: "WEB_DEVELOPMENT",
  MACHINE_LEARNING: "MACHINE_LEARNING",
  DATA_SCIENCE: "DATA_SCIENCE",
  APP_DEVELOPMENT: "APP_DEVELOPMENT",
  GAME_DEVELOPMENT: "GAME_DEVELOPMENT",
  CLOUD_COMPUTING: "CLOUD_COMPUTING",
  DEVOPS: "DEVOPS",
  CYBER_SECURITY: "CYBER_SECURITY",
  BLOCKCHAIN: "BLOCKCHAIN",
  INTERNET_OF_THINGS: "INTERNET_OF_THINGS",
  ROBOTICS: "ROBOTICS",
  VIRTUAL_REALITY: "VIRTUAL_REALITY",
  AUGMENTED_REALITY: "AUGMENTED_REALITY",
  COMPETITIVE_PROGRAMMING: "COMPETITIVE_PROGRAMMING",
} as const;

export type Domain = (typeof domain)[keyof typeof domain];

export const domainEnumList = Object.values(domain) as [Domain, ...Domain[]];
